name: XML Transformer CI

on: [push]

jobs:
  jvm-clj:

    runs-on: ubuntu-latest
    
    container:
      image:  clojure:openjdk-11-tools-deps-slim-buster
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: clojure -P
    - name: Run tests
      run: clojure -X:test
